# Header
menu:
  首页: /
  关于: /about
  存档: /archives
# rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- recent_posts
- archive
# - tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

rocket_to_top: true

# Miscellaneous
# google_analytics:
# gauges_analytics:
favicon: /favicon.png
github: ziqin
# twitter:
# google_plus:
# fb_admins:
# fb_app_id:
