backend:
  name: github
  repo: ziqin/blog
  branch: master
publish_mode: editorial_workflow
media_folder: source/img/uploads
public_folder: /img/uploads
collections:
  - name: post
    label: Post
    folder: source/_posts
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Title
        widget: string
      - name: date
        label: Publish Date
        widget: datetime
      - name: categories
        label: Categories
        widget: list
        field:
          name: category
          label: Category
          widget: string
      - name: tags
        label: Tags
        widget: list
        field:
          name: tag
          label: Tag
          widget: string
      - name: body
        label: Body
        widget: markdown
